---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bolao-web
  namespace: bolao
spec:
  image: ghcr.io/raolivei/bolao-web
  interval: 30m
  secretRef:
    name: ghcr-secret
