apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nima
  namespace: nima
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/eldertree-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  targetNamespace: nima
  upgrade:
    cleanupOnFail: true
  values:
    # ============================================================
    # NIMA - AI/ML learning (currently disabled)
    # ============================================================

    components:
      nima-api:
        image:
          repository: ghcr.io/raolivei/nima-api
          tag: v0.5.0 # {"$imagepolicy": "nima:nima-api-policy:tag"}
          pullPolicy: Always
        replicas: 0  # Disabled
        port: 8000
        env:
          - name: NIMA_CHECKPOINT_PATH
            value: "/app/experiments/nima_technical/checkpoint_best.pt"
          - name: NIMA_TOKENIZER_PATH
            value: "/app/data/processed/technical_example/tokenizer_bpe.json"
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits: { cpu: "250m", memory: "512Mi" }
        probes:
          path: /health
          liveness: { initialDelaySeconds: 60, periodSeconds: 10 }
          readiness: { initialDelaySeconds: 30, periodSeconds: 5 }
        volumeMounts:
          - name: model-data
            mountPath: /app/experiments
          - name: tokenizer-data
            mountPath: /app/data/processed
        volumes:
          - name: model-data
            persistentVolumeClaim:
              claimName: nima-model-pvc
          - name: tokenizer-data
            persistentVolumeClaim:
              claimName: nima-tokenizer-pvc

      nima-frontend:
        image:
          repository: ghcr.io/raolivei/nima-frontend
          tag: latest
          pullPolicy: Always
        replicas: 0  # Disabled
        port: 3000
        probes:
          path: /
          liveness: { initialDelaySeconds: 30, periodSeconds: 10 }
          readiness: { initialDelaySeconds: 10, periodSeconds: 5 }
        resources:
          requests: { cpu: "50m", memory: "128Mi" }
          limits: { cpu: "100m", memory: "256Mi" }

    # -- Middleware
    middleware:
      redirect-https:
        type: redirectScheme
        scheme: https
        permanent: true

    # -- Ingress
    ingress:
      nima:
        host: nima.eldertree.local
        service: nima-frontend
        port: 3000
        middlewares:
          - nima-redirect-https@kubernetescrd
        tls:
          secretName: nima-tls
          certManager: true
        paths:
          - path: /api
            service: nima-api
            port: 8000

    # -- PVCs
    pvc:
      nima-model-pvc:
        size: 5Gi
        storageClass: local-path
      nima-tokenizer-pvc:
        size: 1Gi
        storageClass: local-path
