---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nima-model-pvc
  namespace: nima
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nima-tokenizer-pvc
  namespace: nima
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

