#!/bin/bash
# Extract CSR and private key from Terraform for pitanga.cloud certificate
#
# This script extracts the CSR and private key generated by Terraform
# so you can use them to create a certificate manually in Cloudflare Dashboard

set -e

OUTPUT_DIR="${1:-.}"

# Change to terraform directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$TERRAFORM_DIR"

# Check if Terraform has been initialized
if [ ! -d ".terraform" ]; then
    echo "Error: Terraform not initialized. Run 'terraform init' first."
    exit 1
fi

# Check if resources exist
if ! terraform state list 2>/dev/null | grep -q "tls_private_key.pitanga_cloud"; then
    echo "Error: Terraform resources not created. Run 'terraform apply' first."
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Get CSR and private key from Terraform state using JSON output
echo "Extracting CSR and private key from Terraform..."
CSR=$(terraform show -json 2>/dev/null | jq -r '.values.root_module.resources[] | select(.type == "tls_cert_request" and .name == "pitanga_cloud") | .values.cert_request_pem' 2>/dev/null || echo "")
KEY=$(terraform show -json 2>/dev/null | jq -r '.values.root_module.resources[] | select(.type == "tls_private_key" and .name == "pitanga_cloud") | .values.private_key_pem' 2>/dev/null || echo "")

if [ -z "$CSR" ] || [ -z "$KEY" ]; then
    echo "Error: Could not retrieve CSR or private key from Terraform state."
    echo "Make sure Terraform has been applied: terraform apply"
    exit 1
fi

# Save to files
CSR_FILE="$OUTPUT_DIR/pitanga.csr"
KEY_FILE="$OUTPUT_DIR/pitanga.key"

echo "$CSR" > "$CSR_FILE"
echo "$KEY" > "$KEY_FILE"

# Set proper permissions
chmod 600 "$KEY_FILE"
chmod 644 "$CSR_FILE"

echo ""
echo "✅ Files created successfully!"
echo ""
echo "Files:"
echo "  CSR:  $CSR_FILE"
echo "  Key:  $KEY_FILE"
echo ""
echo "Next steps:"
echo "1. Go to Cloudflare Dashboard → SSL/TLS → Origin Server"
echo "2. Click 'Create Certificate'"
echo "3. Select 'Upload CSR'"
echo "4. Paste contents of $CSR_FILE"
echo "5. Select hostnames: pitanga.cloud and *.pitanga.cloud"
echo "6. Set validity: 15 years"
echo "7. Copy the certificate"
echo "8. Store in Vault using: ./scripts/store-pitanga-cert-manual.sh <certificate>"

