apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: ./helm/pi-hole
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
      # Prevents K3s ServiceLB from creating svclb pods (kube-vip handles LB)
      loadBalancerClass: kube-vip.io/kube-vip
    config:
      clusterIP: 192.168.2.201
