apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-github-client
  namespace: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dex-github-client
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: secret/dex/github-oauth
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: secret/dex/github-oauth
        property: client-secret
