apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/flux-ui
      version: "0.2.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  targetNamespace: observability
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  # Inject admin password hash from Vault (via ExternalSecret)
  valuesFrom:
    - kind: Secret
      name: flux-ui-admin
      valuesKey: password-hash
      targetPath: weave-gitops.adminUser.passwordHash
  values:
    # Global configuration
    global:
      domain: eldertree.local
      clusterIssuer: ca-cluster-issuer

    # Weave GitOps configuration
    # Values passed to weave-gitops dependency (gitops-server chart)
    weave-gitops:
      enabled: true

      # Auto-restart when secrets change (requires Stakater Reloader)
      podAnnotations:
        reloader.stakater.com/auto: "true"

      # Image override: v0.39.0-rc.2 adds Flux v2 API support (fixes v2beta1 error)
      image:
        repository: ghcr.io/weaveworks/wego-app
        tag: v0.39.0-rc.2

      # Service configuration
      service:
        type: ClusterIP
        port: 9001
      
      # Ingress configuration
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: flux.eldertree.local
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: flux-ui-tls
            hosts:
              - flux.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: ca-cluster-issuer
      
      # Resource limits for Raspberry Pi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      
      # Replica count
      replicaCount: 1
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      
      # Service account
      serviceAccount:
        create: true
        name: flux-ui
      
      # RBAC - Weave GitOps needs cluster-admin to manage Flux resources
      rbac:
        create: true
        clusterRole: true
      
      # Static admin user (password hash injected from Vault via valuesFrom)
      adminUser:
        create: true
        createClusterRole: true
        username: admin

      # OIDC via Dex - enables "Login with OIDC Provider" button
      oidcSecret:
        create: true
        issuerURL: https://dex.eldertree.local
        clientID: weave-gitops
        clientSecret: weave-gitops-dex-secret
        redirectURL: https://flux.eldertree.local/oauth2/callback
        cookieDuration: "24h"

      # Mount Eldertree CA bundle so the OIDC client trusts Dex's CA-signed TLS cert
      extraVolumes:
        - name: ca-bundle
          configMap:
            name: eldertree-ca-bundle
      extraVolumeMounts:
        - name: ca-bundle
          mountPath: /etc/ssl/certs/eldertree-ca.crt
          subPath: ca.crt
          readOnly: true
