apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: observability
  chart:
    spec:
      chart: grafana-agent
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    image:
      repository: grafana/agent
      tag: v0.40.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    configMap:
      create: true
      content: |
        metrics:
          global:
            scrape_interval: 30s
          configs:
            - name: default
              remote_write:
                - url: http://kube-prometheus-stack-kube-prome-prometheus.observability.svc.cluster.local:9090/api/v1/write
              scrape_configs:
                - job_name: 'kubernetes-pods'
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                      action: keep
                      regex: true
                    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                      action: replace
                      target_label: __metrics_path__
                      regex: (.+)
                    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                      action: replace
                      regex: ([^:]+)(?::\d+)?;(\d+)
                      replacement: $1:$2
                      target_label: __address__

