apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: "2.14.0"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    image:
      kedacore:
        repository: ghcr.io/kedacore/keda
        tag: 2.14.0
        pullPolicy: IfNotPresent
      metricsApi:
        repository: ghcr.io/kedacore/keda-metrics-apiserver
        tag: 2.14.0
        pullPolicy: IfNotPresent
    resources:
      operator:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      metricsApiServer:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    watchNamespace: ""
    operator:
      logLevel: info
      logFormat: console
    metricsServer:
      logLevel: 0
      replicas: 1
    webhooks:
      enabled: true
    prometheus:
      metricServer:
        enabled: true
        serviceMonitor:
          enabled: true
      operator:
        enabled: true
        serviceMonitor:
          enabled: true

