apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      version: "3.12.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    image:
      repository: registry.k8s.io/metrics-server/metrics-server
      tag: v0.7.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
    hostNetwork:
      enabled: true
    apiService:
      create: true
    rbac:
      create: true

