apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/monitoring-stack
      version: "0.2.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  targetNamespace: observability
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    prometheus:
      enabled: true
      pushgateway:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - pushgateway.eldertree.local
          tls:
            - secretName: pushgateway-tls
              hosts:
                - pushgateway.eldertree.local
          annotations:
            cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      server:
        # Reduce retention to 7 days (was 15d) to save disk space on node-3
        retention: "7d"
        persistentVolume:
          enabled: true
          size: 8Gi
          storageClass: local-path
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - prometheus.eldertree.local
          tls:
            - secretName: prometheus-tls
              hosts:
                - prometheus.eldertree.local
          annotations:
            cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        # Additional scrape configs for services
        additionalScrapeConfigs:
          - key: pihole-scrape.yaml
            name: pihole-scrape-config
          - key: visage-scrape.yaml
            name: visage-scrape-config
          - key: vault-scrape.yaml
            name: vault-scrape-config
    grafana:
      enabled: true
      adminPassword: admin
      persistence:
        enabled: true
        size: 2Gi
        storageClassName: local-path
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.eldertree.local
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer

