apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: observability
  chart:
    spec:
      chart: netdata
      version: "3.0.0"
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    image:
      repository: netdata/netdata
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: netdata.eldertree.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: netdata-tls
          hosts:
            - netdata.eldertree.local
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi

