apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/weaveworks/weave-gitops
  ref:
    branch: main
