apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: observability
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    # Global configuration
    global:
      domain: eldertree.local
      clusterIssuer: selfsigned-cluster-issuer
      storageClass: local-path
    
    # Prometheus configuration
    prometheus:
      enabled: true
      prometheusSpec:
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.52.0
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 8Gi
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.eldertree.local
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    
    # Alertmanager configuration
    alertmanager:
      enabled: true
      alertmanagerSpec:
        image:
          repository: quay.io/prometheus/alertmanager
          tag: v0.28.0
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - alertmanager.eldertree.local
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    
    # Grafana configuration
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 10.4.2
      admin:
        existingSecret: grafana-admin
        secretKey: admin-password
        userKey: admin-user
      persistence:
        enabled: true
        storageClassName: local-path
        size: 2Gi
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.eldertree.local
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    
    # Node Exporter (DaemonSet)
    nodeExporter:
      enabled: true
      image:
        repository: quay.io/prometheus/node-exporter
        tag: v1.7.0
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
    
    # Kube State Metrics
    kubeStateMetrics:
      enabled: true
      image:
        repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
        tag: v2.10.1
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
    
    # Prometheus Operator
    prometheusOperator:
      enabled: true
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.73.2
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
