apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  # suspend: false # Fixed - updated to newer chart version that fixes API token authentication bug
  interval: 30m
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: cert-manager-issuers
      namespace: flux-system
  chart:
    spec:
      chart: external-dns
      # Version removed to use latest - fixes Cloudflare API token authentication bug
      # Previous version 1.18.0 had bug where EXTERNAL_DNS_CLOUDFLARE_API_TOKEN wasn't read properly
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: api-token
            optional: false
      - name: EXTERNAL_DNS_CLOUDFLARE_PROXIED
        value: "false"
    sources:
      - ingress
      - service
    domainFilters:
      - eldertree.xyz
      - pitanga.cloud
    policy: sync
    registry: txt
    txtOwnerId: k8s-eldertree-cloudflare
    logLevel: info
    logFormat: text
