apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    provider: cloudflare
    env:
      - name: EXTERNAL_DNS_CLOUDFLARE_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: api-token
      - name: EXTERNAL_DNS_CLOUDFLARE_PROXIED
        value: "false"
    sources:
      - ingress
      - service
    domainFilters:
      - eldertree.xyz
    policy: sync
    registry: txt
    txtOwnerId: k8s-eldertree-cloudflare
    logLevel: info
    logFormat: text

