apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: cert-manager-issuers
      namespace: flux-system
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    replicaCount: 2
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: external-dns
            topologyKey: kubernetes.io/hostname
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        # WORKAROUND: Use ClusterIP directly to avoid circular DNS dependency
        # ExternalDNS can't resolve pi-hole.pihole.svc.cluster.local because
        # it depends on DNS working, which creates a circular dependency.
        # TODO: Once DNS is stable, consider using service name or creating
        # a separate BIND service with its own ClusterIP for better stability.
        # Current ClusterIP: 10.43.227.7 (pi-hole service in pihole namespace)
        # Note: ClusterIP may change if service is recreated - consider using service name
        # once DNS is stable, or create separate BIND service with stable ClusterIP
        value: "10.43.227.7"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "5353"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: "eldertree.local"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: "externaldns-key"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-tsig-secret
            key: tsig-secret
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: "hmac-sha256"
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "false"
    sources:
      - ingress
      - service
    domainFilters:
      - eldertree.local
    policy: sync
    registry: txt
    txtOwnerId: k8s-eldertree
    logLevel: info
    logFormat: text
