apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "bind.pihole.svc.cluster.local"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "5353"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: "eldertree.local"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: "externaldns-key"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-tsig-secret
            key: tsig-secret
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: "hmac-sha256"
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "false"
    sources:
      - ingress
      - service
    domainFilters:
      - eldertree.local
    policy: sync
    registry: txt
    txtOwnerId: k8s-eldertree
    logLevel: info
    logFormat: text
