apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./helm/cert-manager-issuers
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    selfSigned:
      enabled: true
      name: selfsigned-cluster-issuer
    acme:
      enabled: false
