apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # See values.yaml for complete configuration reference
    # Key settings optimized for Raspberry Pi ARM64
    defaultSettings:
      defaultReplicaCount: "2"
      replicaSoftAntiAffinity: "false"  # Hard anti-affinity
      defaultDataPath: "/mnt/longhorn"
      defaultFsType: "ext4"
      defaultClass: "false"  # Manual storage class selection
      storageOverProvisioningPercentage: "200"
      storageMinimalAvailablePercentage: "25"
      allowRecurringJobWhileVolumeDetached: "true"
    # Resource limits for Raspberry Pi
    manager:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    engine:
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    instanceManager:
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    csi:
      attacher:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      provisioner:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      resizer:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      snapshotter:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
    ui:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"

