apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: openclaw-secrets
    creationPolicy: Owner
  data:
    # Telegram Bot Token
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: secret/openclaw/telegram
        property: token
    # Google Gemini API Key
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: secret/openclaw/gemini
        property: api-key
    # Gateway Authentication Token
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: secret/openclaw/gateway
        property: token
    # Brave Search API Key (web search)
    - secretKey: BRAVE_API_KEY
      remoteRef:
        key: secret/openclaw/brave
        property: BRAVE_API_KEY
