apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: openclaw
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "raolivei",
                "password": "{{ .token }}",
                "auth": "{{ printf `raolivei:%s` .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        # Reuse existing GHCR token from canopy
        key: secret/canopy/ghcr-token
        property: token
