apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grove-data
  namespace: openclaw
  labels:
    app: openclaw
    component: grove
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
