apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grove-secrets
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grove-secrets
    creationPolicy: Owner
  data:
    # GitHub App credentials
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: secret/grove/github-app
        property: app-id
    - secretKey: GITHUB_APP_INSTALLATION_ID
      remoteRef:
        key: secret/grove/github-app
        property: installation-id
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: secret/grove/github-app
        property: private-key
    # API authentication key (for OpenClaw -> Grove calls)
    - secretKey: API_KEY
      remoteRef:
        key: secret/grove/api-key
        property: key
