apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: grove-image-updates
  namespace: openclaw
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore: update grove image to {{range .Changed.Changes}}{{.NewValue}}{{end}}"
    push:
      branch: flux/grove-image-updates
  update:
    path: ./clusters/eldertree/openclaw
    strategy: Setters
