---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: grove-image-updates
  namespace: openclaw
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(grove): update image to {{range .Changed.Objects}}{{println .NewValue}}{{end}}"
    push:
      branch: main
  update:
    path: ./clusters/eldertree/openclaw
    strategy: Setters
