apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw
  namespace: openclaw
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/eldertree-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  targetNamespace: openclaw
  upgrade:
    cleanupOnFail: true
  values:
    # ============================================================
    # OpenClaw - LLM gateway + Grove AI agent
    # ============================================================

    components:
      openclaw:
        image:
          repository: ghcr.io/raolivei/openclaw
          tag: latest
          pullPolicy: Always
        port: 18789
        strategy: Recreate
        serviceAccountName: openclaw
        podAnnotations:
          deployment.kubernetes.io/revision: "2026-01-31-v1.0.0"
        args: ["--bind", "lan"]
        env:
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: openclaw-secrets
                key: GOOGLE_API_KEY
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: openclaw-secrets
                key: TELEGRAM_BOT_TOKEN
          - name: OPENCLAW_GATEWAY_TOKEN
            valueFrom:
              secretKeyRef:
                name: openclaw-secrets
                key: OPENCLAW_GATEWAY_TOKEN
          - name: BRAVE_API_KEY
            valueFrom:
              secretKeyRef:
                name: openclaw-secrets
                key: BRAVE_API_KEY
          - name: HOME
            value: /home/node
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1536"
        envFrom:
          - configMapRef:
              name: openclaw-config
        resources:
          requests: { cpu: "200m", memory: "1Gi" }
          limits: { cpu: "1000m", memory: "2Gi" }
        probes:
          path: /health
          port: 18789
          liveness: { initialDelaySeconds: 120, periodSeconds: 30, timeoutSeconds: 10 }
          readiness: { initialDelaySeconds: 90, periodSeconds: 10, timeoutSeconds: 5 }
        volumeMounts:
          - name: openclaw-data
            mountPath: /home/node/.openclaw
          - name: skills
            mountPath: /home/node/.openclaw/skills
            readOnly: true
        volumes:
          - name: openclaw-data
            persistentVolumeClaim:
              claimName: openclaw-data
          - name: skills
            configMap:
              name: openclaw-skills

      grove:
        image:
          repository: ghcr.io/raolivei/grove
          tag: v0.2.0 # {"$imagepolicy": "openclaw:grove:tag"}
          pullPolicy: Always
        port: 8006
        servicePort: 8000
        strategy: Recreate
        serviceAccountName: grove
        envFrom:
          - configMapRef:
              name: grove-config
        env:
          - name: GROVE_PORT
            value: "8006"
          - name: GROVE_K8S_IN_CLUSTER
            value: "true"
          - name: GROVE_REPOS_DIR
            value: "/data/repos"
          - name: GROVE_APPROVAL_DB_PATH
            value: "/data/approvals.db"
          - name: GROVE_API_KEY
            valueFrom:
              secretKeyRef:
                name: grove-secrets
                key: API_KEY
          - name: GROVE_GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: grove-secrets
                key: GITHUB_APP_ID
          - name: GROVE_GITHUB_APP_INSTALLATION_ID
            valueFrom:
              secretKeyRef:
                name: grove-secrets
                key: GITHUB_APP_INSTALLATION_ID
          - name: GROVE_GITHUB_APP_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: grove-secrets
                key: GITHUB_APP_PRIVATE_KEY
        resources:
          requests: { cpu: "250m", memory: "256Mi" }
          limits: { cpu: "500m", memory: "512Mi" }
        probes:
          path: /health
          port: 8006
          liveness: { initialDelaySeconds: 30, periodSeconds: 30, timeoutSeconds: 10 }
          readiness: { initialDelaySeconds: 10, periodSeconds: 10, timeoutSeconds: 5 }
        volumeMounts:
          - name: grove-data
            mountPath: /data
        volumes:
          - name: grove-data
            persistentVolumeClaim:
              claimName: grove-data

    # -- Middleware
    middleware:
      redirect-https:
        type: redirectScheme
        scheme: https
        permanent: true
      add-token-header:
        type: headers
        headers:
          customRequestHeaders:
            X-OpenClaw-Token: "851da3d676fec9cacfc9cc5ea6233b2126a28f815c5757b40c5a5d71857b1a41"
            Authorization: "Bearer 851da3d676fec9cacfc9cc5ea6233b2126a28f815c5757b40c5a5d71857b1a41"

    # -- Ingress
    ingress:
      openclaw-web:
        host: openclaw.eldertree.local
        service: openclaw
        port: 18789
        middlewares:
          - openclaw-redirect-https@kubernetescrd
          - openclaw-add-token-header@kubernetescrd
        tls:
          secretName: openclaw-tls
          certManager: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: openclaw.eldertree.local

      grove:
        host: grove.eldertree.local
        service: grove
        port: 8000
        tls:
          secretName: grove-tls
          certManager: true
