apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-data
  namespace: openclaw
  labels:
    app: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  # Using local-path (k3s default) - Longhorn was removed from cluster
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
