apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  chart:
    spec:
      chart: ./pi-fleet/helm/monitoring-stack
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    global:
      domain: eldertree.local
      clusterIssuer: selfsigned-cluster-issuer
      storageClass: local-path
    prometheus:
      enabled: true
    grafana:
      enabled: true

