apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-storage
  namespace: eldertree-docs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-nvme
