apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ollie-runner-github-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ollie-runner-github-secret
    creationPolicy: Owner
    template:
      data:
        github_token: "{{ .github_token }}"
  data:
    - secretKey: github_token
      remoteRef:
        key: secret/eldertree/arc-runners/ollie
        property: github_token
