apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager-issuers
      namespace: flux-system
  chart:
    spec:
      chart: vault
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    server:
      dev:
        enabled: false  # Production mode with persistence
      
      # Enable persistence for secrets
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: local-path
        accessMode: ReadWriteOnce
      
      # Standalone mode (single-node cluster)
      ha:
        enabled: false
      standalone:
        enabled: true
        config: |
          ui = true
          
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          
          storage "file" {
            path = "/vault/data"
          }
          
          # Disable mlock for non-root containers
          disable_mlock = true
      
      replicas: 1
      ui:
        enabled: true
        serviceType: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: vault.eldertree.local
        tls:
          - secretName: vault-tls
            hosts:
              - vault.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    injector:
      enabled: true
