apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secret
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-token
      remoteRef:
        key: secret/external-dns/cloudflare-api-token
        property: api-token
  # Allow ExternalSecret to exist even if secret doesn't exist in Vault yet
  # This prevents pod failures when Vault is sealed or secret hasn't been created

