apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-system
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: flux-system
    creationPolicy: Owner
  data:
    - secretKey: identity
      remoteRef:
        key: secret/pi-fleet/flux/git
        property: sshKey

