apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nima-secrets
  namespace: nima
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nima-secrets
    creationPolicy: Owner
  # No secrets currently required for NIMA
  # When secrets are needed, add them here:
  # data:
  #   - secretKey: API_KEY
  #     remoteRef:
  #       key: secret/nima/app
  #       property: api-key

