apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: pihole-secrets
    creationPolicy: Owner
  data:
    - secretKey: webpassword
      remoteRef:
        key: secret/pi-fleet/pihole/webpassword
        property: password

