apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: us-law-severity-map-secrets
  namespace: us-law-severity-map
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: us-law-severity-map-secrets
    creationPolicy: Owner
  data:
    - secretKey: MAPBOX_TOKEN
      remoteRef:
        key: secret/us-law-severity-map/mapbox
        property: token

