apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: journey-postgres-pvc
  namespace: journey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # For Pi cluster with local-path provisioner

