apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  values:
    defaultSettings:
      defaultReplicaCount: 1
      defaultDataPath: /var/lib/longhorn
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.eldertree.local
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
