apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
    speaker:
      memberlist:
        enabled: true
      # Required for L2 mode to add VIP addresses to network interfaces
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
          drop:
            - ALL


