apiVersion: batch/v1
kind: Job
metadata:
  name: build-swimto-images
  namespace: swimto
spec:
  template:
    spec:
      containers:
        - name: build
          image: docker:dind
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              apk add --no-cache git
              
              # Setup Docker config (copy to writable location)
              mkdir -p /root/.docker
              cp /config/config.json /root/.docker/config.json
              
              # Start docker daemon
              dockerd-entrypoint.sh &
              until docker info >/dev/null 2>&1; do sleep 1; done
              
              # Clone repo and get version
              git clone https://github.com/raolivei/swimTO.git /workspace
              cd /workspace
              VERSION=$(cat VERSION | tr -d '[:space:]')
              
              # Build and push images
              docker build -t ghcr.io/raolivei/swimto-api:v${VERSION} -f apps/api/Dockerfile .
              docker build -t ghcr.io/raolivei/swimto-web:v${VERSION} -f apps/web/Dockerfile apps/web
              docker push ghcr.io/raolivei/swimto-api:v${VERSION}
              docker push ghcr.io/raolivei/swimto-web:v${VERSION}
              
              echo "✅ Build complete: v${VERSION}"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: workspace
          emptyDir: {}
        - name: config
          secret:
            secretName: ghcr-secret
            items:
              - key: .dockerconfigjson
                path: config.json
      restartPolicy: Never
  backoffLimit: 0
