apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-longhorn
  namespace: swimto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Using Longhorn for distributed storage with replication
  storageClassName: longhorn

