apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    server:
      dev:
        enabled: true
      replicas: 1
      ui:
        enabled: true
        serviceType: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: vault.eldertree.local
        tls:
          - secretName: vault-tls
            hosts:
              - vault.eldertree.local
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    injector:
      enabled: true
