# Manual GHCR Secret (temporary workaround)
# This creates the secret directly without Vault/ExternalSecret
#
# Usage:
#   1. Replace YOUR_GITHUB_TOKEN below with your actual token
#   2. Run: kubectl apply -f ghcr-secret-manual.yaml
#   3. Or use: kubectl create secret docker-registry ghcr-secret \
#        --docker-server=ghcr.io \
#        --docker-username=raolivei \
#        --docker-password="YOUR_TOKEN" \
#        -n pitanga

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: pitanga
type: kubernetes.io/dockerconfigjson
data:
  # This is base64 encoded docker config JSON
  # To generate: echo -n '{"auths":{"ghcr.io":{"username":"raolivei","password":"YOUR_TOKEN","auth":"BASE64(raolivei:YOUR_TOKEN)"}}}' | base64
  # Or use: kubectl create secret docker-registry ghcr-secret --dry-run=client -o yaml
  .dockerconfigjson: REPLACE_WITH_BASE64_ENCODED_DOCKER_CONFIG
