---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-api
  namespace: canopy
  labels:
    app: canopy
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy
      component: api
  template:
    metadata:
      labels:
        app: canopy
        component: api
    spec:
      containers:
      - name: api
        image: ghcr.io/raolivei/canopy-api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: canopy-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://canopy-redis:6379/0"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-frontend
  namespace: canopy
  labels:
    app: canopy
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy
      component: frontend
  template:
    metadata:
      labels:
        app: canopy
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/raolivei/canopy-frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://canopy-api:8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-redis
  namespace: canopy
  labels:
    app: canopy
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy
      component: redis
  template:
    metadata:
      labels:
        app: canopy
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canopy-postgres
  namespace: canopy
  labels:
    app: canopy
    component: postgres
spec:
  serviceName: canopy-postgres
  replicas: 1
  selector:
    matchLabels:
      app: canopy
      component: postgres
  template:
    metadata:
      labels:
        app: canopy
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: canopy
        - name: POSTGRES_USER
          value: canopy
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: canopy-secrets
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi

