---
# PodDisruptionBudgets for critical infrastructure components
# Ensures at least 1 replica is always available during maintenance

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cloudflared
---
# MetalLB PDB removed - kube-vip now handles LoadBalancer services
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cert-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-dns
  namespace: external-dns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns-cloudflare
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traefik
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
