apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-workspace
  namespace: github-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
