apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: personal-website
  namespace: personal-website
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/eldertree-app
      version: "0.1.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  targetNamespace: personal-website
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    components:
      personal-website:
        image:
          repository: ghcr.io/raolivei/personal-website
          tag: v0.1.0 # {"$imagepolicy": "personal-website:personal-website-policy:tag"}
          pullPolicy: IfNotPresent
        port: 80
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 101
          fsGroup: 101
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "100m", memory: "128Mi" }
        probes:
          path: /
          liveness: { initialDelaySeconds: 10, periodSeconds: 15 }
          readiness: { initialDelaySeconds: 5, periodSeconds: 10 }
        volumeMounts:
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-run
            mountPath: /var/run
        volumes:
          - name: nginx-cache
            emptyDir: {}
          - name: nginx-run
            emptyDir: {}

    ingress:
      personal-website-public:
        host: raolivei.me
        hosts:
          - www.raolivei.me
        service: personal-website
        port: 80
        tls:
          secretName: raolivei-cloudflare-origin-tls
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "raolivei.me,www.raolivei.me"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
